version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/springboot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "user"
    groups:
      backend:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "user"
    groups:
      admin:
        patterns:
          - "*"