version: 2

updates:
  - package-ecosystem: "maven"
    directory: "/springboot"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "user"
    groups:
      backend:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
      - dependency-name: "org.mybatis.spring.boot:mybatis-spring-boot-starter"
      - dependency-name: "me.paulschwarz:spring-dotenv"
      - dependency-name: "software.amazon.awssdk:s3"

  - package-ecosystem: "npm"
    directory: "/admin"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "user"
    groups:
      admin:
        patterns:
          - "*"